# Generated by Django 3.2.15 on 2022-11-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='货币中文名')),
                ('name', models.CharField(max_length=100, verbose_name='货币英文名')),
                ('current_price', models.CharField(max_length=100, verbose_name='货币最新价')),
                ('high_price', models.CharField(max_length=100, verbose_name='24小时最高价')),
                ('low_price', models.CharField(max_length=100, verbose_name='24小时最低价')),
                ('vol', models.CharField(max_length=100, verbose_name='24小时成交量')),
                ('logo', models.CharField(max_length=500, verbose_name='货币图标')),
                ('marketcap', models.CharField(max_length=100, verbose_name='市值')),
            ],
            options={
                'db_table': 'tb_currency',
            },
        ),
        migrations.CreateModel(
            name='DealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=50, verbose_name='交易对名字')),
                ('collect', models.IntegerField(verbose_name='收值')),
                ('open', models.IntegerField(verbose_name='开值')),
                ('limit_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='货币涨跌幅')),
                ('top_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最高值')),
                ('floor_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最低值')),
                ('turnover', models.DecimalField(decimal_places=3, max_digits=30, verbose_name='24小时成交量')),
                ('switch', models.BooleanField(default=1, verbose_name='是否显示的开关')),
            ],
            options={
                'db_table': 'tb_deal',
            },
        ),
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chinese', models.CharField(max_length=100, verbose_name='交易所中文名')),
                ('name_english', models.CharField(max_length=100, verbose_name='交易所英文名')),
                ('official_address', models.CharField(max_length=500, verbose_name='官网地址')),
                ('icon', models.CharField(max_length=500, verbose_name='交易所图标')),
                ('description', models.CharField(max_length=500, verbose_name='交易所描述')),
                ('count_deal', models.IntegerField(verbose_name='交易对总数')),
            ],
            options={
                'db_table': 'tb_exchange',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.IntegerField(verbose_name='开值')),
                ('high', models.IntegerField(verbose_name='高值')),
                ('down', models.IntegerField(verbose_name='低值')),
                ('collect', models.IntegerField(verbose_name='收值')),
                ('limit_price', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='货币涨跌幅')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='所属时间')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.currencymodel', verbose_name='币id')),
                ('deal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.dealmodel', verbose_name='交易对儿名称')),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchangemodel', verbose_name='交易所id')),
            ],
            options={
                'db_table': 'tb_transaction_history',
            },
        ),
        migrations.CreateModel(
            name='KLine1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(max_length=100, verbose_name='开值')),
                ('high', models.CharField(max_length=100, verbose_name='高值')),
                ('down', models.CharField(max_length=100, verbose_name='低值')),
                ('collect', models.CharField(max_length=100, verbose_name='收值')),
                ('limit_price', models.CharField(max_length=1024, verbose_name='货币涨跌幅')),
                ('minute_num', models.CharField(max_length=100, verbose_name='一分钟成交量')),
                ('along_time', models.CharField(max_length=1024, verbose_name='时间戳')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.currencymodel', verbose_name='币id')),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchangemodel', verbose_name='交易所id')),
            ],
            options={
                'db_table': 'tb_1mKline',
            },
        ),
        migrations.CreateModel(
            name='KLine15Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(max_length=100, verbose_name='开值')),
                ('high', models.CharField(max_length=100, verbose_name='高值')),
                ('down', models.CharField(max_length=100, verbose_name='低值')),
                ('collect', models.CharField(max_length=100, verbose_name='收值')),
                ('limit_price', models.CharField(max_length=1024, verbose_name='货币涨跌幅')),
                ('minute_num', models.CharField(max_length=100, verbose_name='十五分钟成交量')),
                ('along_time', models.CharField(max_length=1024, verbose_name='时间戳')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.currencymodel', verbose_name='币id')),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchangemodel', verbose_name='交易所id')),
            ],
            options={
                'db_table': 'tb_15mKline',
            },
        ),
        migrations.CreateModel(
            name='DealRelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100, verbose_name='货币名字')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.currencymodel', verbose_name='币id')),
            ],
            options={
                'db_table': 'tb_deal_relation',
            },
        ),
        migrations.AddField(
            model_name='dealmodel',
            name='exchange_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchangemodel', verbose_name='交易所id'),
        ),
        migrations.CreateModel(
            name='CurrencyHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='当前价格')),
                ('price_time', models.DateTimeField(auto_now_add=True, verbose_name='价格所属时间')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.currencymodel', verbose_name='币id')),
            ],
            options={
                'db_table': 'tb_currency_history',
            },
        ),
    ]
