# Generated by Django 3.2.15 on 2022-10-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='币名')),
                ('abbre_name', models.CharField(max_length=30, unique=True, verbose_name='缩写')),
                ('icon', models.CharField(max_length=680, verbose_name='图标')),
                ('shuffle', models.IntegerField(unique=True, verbose_name='排行')),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='当前价格')),
                ('market', models.DecimalField(decimal_places=0, max_digits=30, verbose_name='市值')),
                ('turnover', models.IntegerField(verbose_name='24成交量')),
                ('minimum', models.IntegerField(verbose_name='最低')),
                ('highest', models.IntegerField(verbose_name='最高')),
            ],
            options={
                'verbose_name_plural': '币种表',
                'db_table': 'tb_currency',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='交易所名称')),
                ('img', models.CharField(max_length=1026, verbose_name='交易所地址')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='')),
                ('sum', models.IntegerField(verbose_name='总数')),
            ],
            options={
                'verbose_name_plural': '交易所表',
                'db_table': 'tb_exchange',
            },
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal', models.BooleanField(default=False, verbose_name='是否显示')),
                ('name', models.CharField(max_length=20, verbose_name='交易对名称')),
                ('open', models.IntegerField(verbose_name='开值')),
                ('high', models.IntegerField(verbose_name='高值')),
                ('down', models.IntegerField(verbose_name='低值')),
                ('collect', models.IntegerField(verbose_name='收值')),
                ('price_limit', models.IntegerField(verbose_name='涨跌幅')),
                ('cion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='business.coin', verbose_name='币id')),
                ('cions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.coin', verbose_name='币id')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchange', verbose_name='交易所')),
            ],
            options={
                'db_table': 'tb_trading',
            },
        ),
        migrations.CreateModel(
            name='K_line_fifteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=64, verbose_name='交易对名字')),
                ('open', models.IntegerField(verbose_name='开值')),
                ('high', models.IntegerField(verbose_name='高值')),
                ('down', models.IntegerField(verbose_name='低值')),
                ('collect', models.IntegerField(verbose_name='收值')),
                ('price_limit', models.IntegerField(verbose_name='涨跌幅')),
                ('minute_num', models.IntegerField(verbose_name='十五分钟成交量')),
                ('minute_price', models.IntegerField(verbose_name='十五分钟成交额度')),
                ('deal_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.coin', verbose_name='虚拟货币id')),
                ('ex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchange', verbose_name='交易所id')),
            ],
            options={
                'verbose_name_plural': '15分钟k值',
                'db_table': 'tb_line_fifteen',
            },
        ),
        migrations.CreateModel(
            name='K_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=64, verbose_name='交易对名字')),
                ('open', models.IntegerField(verbose_name='开值')),
                ('high', models.IntegerField(verbose_name='高值')),
                ('down', models.IntegerField(verbose_name='低值')),
                ('collect', models.IntegerField(verbose_name='收值')),
                ('price_limit', models.IntegerField(verbose_name='涨跌幅')),
                ('minute_num', models.IntegerField(verbose_name='一分钟成交量')),
                ('minute_price', models.IntegerField(verbose_name='一分钟成交额度')),
                ('deal_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.coin', verbose_name='虚拟货币id')),
                ('ex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchange', verbose_name='交易所id')),
            ],
            options={
                'verbose_name_plural': '1分钟k值',
                'db_table': 'tb_k_line',
            },
        ),
        migrations.CreateModel(
            name='History_Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='所属时间')),
                ('name', models.CharField(max_length=20, verbose_name='交易对名称')),
                ('open', models.IntegerField(verbose_name='开值')),
                ('high', models.IntegerField(verbose_name='高值')),
                ('down', models.IntegerField(verbose_name='低值')),
                ('collect', models.IntegerField(verbose_name='收值')),
                ('price_limit', models.IntegerField(verbose_name='涨跌幅')),
                ('cion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.coin', verbose_name='币id')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.exchange', verbose_name='交易所')),
            ],
            options={
                'db_table': 'tb_history_exchange',
            },
        ),
        migrations.CreateModel(
            name='History_coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='当前价格')),
                ('new_time', models.CharField(max_length=90, verbose_name='价格最新时间')),
                ('cion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.coin', verbose_name='币id')),
            ],
            options={
                'verbose_name_plural': '币历史表',
                'db_table': 'tb_history',
            },
        ),
    ]
